variable "vpc_id" {}
variable "kms_key_id" {}
variable "db_sg_id" {}
variable "db_identifier" {}
variable "db_engine" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_allocated_storage" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_subnetgroup_name" {}
